### ISSUE TITLE
How to check a list of IPs against the blacklist?

### ISSUE THREAD

**Issue by SunnyVirk007** [adionditsak/blacklist-check-unix-linux-utility#10]
How to check a list of IPs against the blacklist?

PS: Sorry, I know it's not an issue but a query, I didn't know where else to place this.

**Comment by adionditsak** [comment]
Not really relevant for this repository, but you can do it in many ways in the shell, with a simple one below.

Let's say you have a file called `ips.txt` with a list of IPs.

```
while IFS= read -r LINE; do
    ./bl "$LINE"
done < ips.txt
```

This would run the command with the input from each line which would be the IP.

Closing this issue.
