### ISSUE TITLE
Why the script reverse the IPs?

### ISSUE THREAD

**Issue by radixtenshi** [adionditsak/blacklist-check-unix-linux-utility#4]
I just ask why when you make a query for some IP A.B.C.D you see the imverted order of the numbers.. example:

D.C.B.A.black.uribl.com

![imagen](https://user-images.githubusercontent.com/4320793/44114687-4d6f9fbe-9fe2-11e8-9e5a-d1ed0ca237ae.png)

**Comment by adionditsak** [comment]
This is how reverse lookup looks like @radixtenshi
