### ISSUE TITLE
Unexpected activity

### ISSUE THREAD

**Issue by BustedSec** [adionditsak/blacklist-check-unix-linux-utility#6]
Regardless of what IP I check I tend to get back the result [not listed] or [blacklisted] (92.242.140.21). I did not ask to check 92,242.140.21 yet it pops up in the results regardless of what IP I check, even local ones like 127.0.0.1 that shouldn't be found at all. 

here is the output  
/bl 127.0.0.1
You entered an IP: 127.0.0.1
127.0.0.1 name localhost.
20-06-03_Jun:06:1591212528_-0400 1.0.0.127.0spam.fusionzero.com.        [not listed]
20-06-03_Jun:06:1591212528_-0400 1.0.0.127.access.redhawk.org.          [blacklisted] (92.242.140.21)                                    
20-06-03_Jun:06:1591212528_-0400 1.0.0.127.all.s5h.net.                 [blacklisted] (92.242.140.21)                                    
20-06-03_Jun:06:1591212528_-0400 1.0.0.127.all.spamrats.com.            [blacklisted] (92.242.140.21)                                    
20-06-03_Jun:06:1591212528_-0400 1.0.0.127.aspews.ext.sorbs.net.        [blacklisted] (92.242.140.21)                                    
20-06-03_Jun:06:1591212530_-0400 1.0.0.127.babl.rbl.webiron.net.        [not listed]                                                     
20-06-03_Jun:06:1591212537_-0400 1.0.0.127.backscatter.spameatingmonkey.net.[blacklisted] (92.242.140.21)                                
20-06-03_Jun:06:1591212537_-0400 1.0.0.127.b.barracudacentral.org.      [blacklisted] (92.242.140.21)                                    
20-06-03_Jun:06:1591212537_-0400 1.0.0.127.bb.barracudacentral.org.     [blacklisted] (92.242.140.21)                                    
20-06-03_Jun:06:1591212537_-0400 1.0.0.127.black.junkemailfilter.com.   [blacklisted] (92.242.140.21)                                    
20-06-03_Jun:06:1591212537_-0400 1.0.0.127.bl.blocklist.de.             [blacklisted] (92.242.140.21)                                    
20-06-03_Jun:06:1591212537_-0400 1.0.0.127.bl.drmx.org.                 [blacklisted] (92.242.140.21)                                    
20-06-03_Jun:06:1591212538_-0400 1.0.0.127.bl.konstant.no.              [blacklisted] (92.242.140.21)                                    
20-06-03_Jun:06:1591212538_-0400 1.0.0.127.bl.mailspike.net.            [blacklisted] (92.242.140.21)                                    
20-06-03_Jun:06:1591212538_-0400 1.0.0.127.bl.nosolicitado.org.         [blacklisted] (92.242.140.21)                                    
20-06-03_Jun:06:1591212539_-0400 1.0.0.127.bl.nszones.com.              [blacklisted] (92.242.140.21)                                    
20-06-03_Jun:06:1591212539_-0400 1.0.0.127.block.dnsbl.sorbs.net.       [blacklisted] (92.242.140.21)                                    
20-06-03_Jun:06:1591212539_-0400 1.0.0.127.bl.rbl.scrolloutf1.com.      [blacklisted] (92.242.140.21)                                    
20-06-03_Jun:06:1591212539_-0400 1.0.0.127.bl.scientificspam.net.       [blacklisted] (92.242.140.21)                                    
20-06-03_Jun:06:1591212539_-0400 1.0.0.127.bl.score.senderscore.com.    [blacklisted] (92.242.140.21)                                    
20-06-03_Jun:06:1591212539_-0400 1.0.0.127.bl.spamcop.net.              [blacklisted] (92.242.140.21)                                    
20-06-03_Jun:06:1591212539_-0400 1.0.0.127.bl.spameatingmonkey.net.     [blacklisted] (92.242.140.21)                                    
20-06-03_Jun:06:1591212539_-0400 1.0.0.127.bl.suomispam.net.            [blacklisted] (92.242.140.21)                                    
20-06-03_Jun:06:1591212540_-0400 1.0.0.127.bsb.empty.us.                [blacklisted] (92.242.140.21)                                    
20-06-03_Jun:06:1591212540_-0400 1.0.0.127.cart00ney.surriel.com.       [blacklisted] (92.242.140.21)                                    
20-06-03_Jun:06:1591212540_-0400 1.0.0.127.cbl.abuseat.org.             [blacklisted] (92.242.140.21)                                    
20-06-03_Jun:06:1591212540_-0400 1.0.0.127.cbl.anti-spam.org.cn.        [not listed]                                                     
20-06-03_Jun:06:1591212540_-0400 1.0.0.127.cblless.anti-spam.org.cn.    [not listed]                                                     
20-06-03_Jun:06:1591212540_-0400 1.0.0.127.cblplus.anti-spam.org.cn.    [not listed]                                                     
20-06-03_Jun:06:1591212540_-0400 1.0.0.127.cdl.anti-spam.org.cn.        [not listed]                                                     
20-06-03_Jun:06:1591212541_-0400 1.0.0.127.combined.rbl.msrbl.net.      [blacklisted] (92.242.140.21)                                    
20-06-03_Jun:06:1591212541_-0400 1.0.0.127.db.wpbl.info.                [blacklisted] (92.242.140.21)                                    
20-06-03_Jun:06:1591212541_-0400 1.0.0.127.dnsbl-1.uceprotect.net.      [blacklisted] (92.242.140.21)                                    
20-06-03_Jun:06:1591212541_-0400 1.0.0.127.dnsbl-2.uceprotect.net.      [blacklisted] (92.242.140.21)                                    
20-06-03_Jun:06:1591212541_-0400 1.0.0.127.dnsbl-3.uceprotect.net.      [blacklisted] (92.242.140.21)                                    
20-06-03_Jun:06:1591212541_-0400 1.0.0.127.dnsbl.cobion.com.            [blacklisted] (92.242.140.21)                                    
20-06-03_Jun:06:1591212541_-0400 1.0.0.127.dnsbl.dronebl.org.           [blacklisted] (92.242.140.21)                                    
20-06-03_Jun:06:1591212541_-0400 1.0.0.127.dnsbl.justspam.org.          [blacklisted] (92.242.140.21)                                    
20-06-03_Jun:06:1591212541_-0400 1.0.0.127.dnsbl.kempt.net.             [blacklisted] (92.242.140.21)                                    
20-06-03_Jun:06:1591212541_-0400 1.0.0.127.dnsbl.net.ua.                [blacklisted] (92.242.140.21)                                    
20-06-03_Jun:06:1591212542_-0400 1.0.0.127.dnsbl.rv-soft.info.          [not listed]                                                     
20-06-03_Jun:06:1591212542_-0400 1.0.0.127.dnsbl.rymsho.ru.             [blacklisted] (92.242.140.21)                                    
20-06-03_Jun:06:1591212542_-0400 1.0.0.127.dnsbl.sorbs.net.             [blacklisted] (92.242.140.21)                                    
20-06-03_Jun:06:1591212542_-0400 1.0.0.127.dnsbl.spfbl.net.             [blacklisted] (92.242.140.21)                                    
20-06-03_Jun:06:1591212542_-0400 1.0.0.127.dnsbl.tornevall.org.         [blacklisted] (92.242.140.21)                                    
20-06-03_Jun:06:1591212543_-0400 1.0.0.127.dnsbl.zapbl.net.             [blacklisted] (92.242.140.21)                                    
20-06-03_Jun:06:1591212543_-0400 1.0.0.127.dnsrbl.org.                  [not listed]                                                     
20-06-03_Jun:06:1591212546_-0400 1.0.0.127.dnsrbl.swinog.ch.            [blacklisted] (92.242.140.21)                                    
20-06-03_Jun:06:1591212546_-0400 1.0.0.127.dul.dnsbl.sorbs.net.         [blacklisted] (92.242.140.21)                                    
20-06-03_Jun:06:1591212547_-0400 1.0.0.127.dyna.spamrats.com.           [blacklisted] (92.242.140.21)                                    
20-06-03_Jun:06:1591212547_-0400 1.0.0.127.dyn.nszones.com.             [blacklisted] (92.242.140.21)                                    
20-06-03_Jun:06:1591212547_-0400 1.0.0.127.escalations.dnsbl.sorbs.net. [blacklisted] (92.242.140.21)                                    
20-06-03_Jun:06:1591212549_-0400 1.0.0.127.fnrbl.fast.net.              [blacklisted] (92.242.140.21)                                    
20-06-03_Jun:06:1591212549_-0400 1.0.0.127.hostkarma.junkemailfilter.com.[not listed]                                                    
20-06-03_Jun:06:1591212549_-0400 1.0.0.127.http.dnsbl.sorbs.net.        [blacklisted] (92.242.140.21)                                    
20-06-03_Jun:06:1591212550_-0400 1.0.0.127.images.rbl.msrbl.net.        [blacklisted] (92.242.140.21)                                    
20-06-03_Jun:06:1591212550_-0400 1.0.0.127.invaluement.                 [blacklisted] (92.242.140.21)                                    
20-06-03_Jun:06:1591212550_-0400 1.0.0.127.ips.backscatterer.org.       [blacklisted] (92.242.140.21)                                    
20-06-03_Jun:06:1591212550_-0400 1.0.0.127.ix.dnsbl.manitu.net.         [blacklisted] (92.242.140.21)                                    
20-06-03_Jun:06:1591212551_-0400 1.0.0.127.l1.bbfh.ext.sorbs.net.       [blacklisted] (92.242.140.21)                                    
20-06-03_Jun:06:1591212552_-0400 1.0.0.127.l2.bbfh.ext.sorbs.net.       [blacklisted] (92.242.140.21)                                    
20-06-03_Jun:06:1591212553_-0400 1.0.0.127.l4.bbfh.ext.sorbs.net.       [blacklisted] (92.242.140.21)                                    
20-06-03_Jun:06:1591212554_-0400 1.0.0.127.list.bbfh.org.               [blacklisted] (92.242.140.21)                                    
20-06-03_Jun:06:1591212554_-0400 1.0.0.127.mail-abuse.blacklist.jippg.org.[blacklisted] (92.242.140.21)                                  
20-06-03_Jun:06:1591212555_-0400 1.0.0.127.misc.dnsbl.sorbs.net.        [blacklisted] (92.242.140.21)                                    
20-06-03_Jun:06:1591212555_-0400 1.0.0.127.multi.surbl.org.             [blacklisted] (92.242.140.21)                                    
20-06-03_Jun:06:1591212555_-0400 1.0.0.127.netscan.rbl.blockedservers.com.[blacklisted] (92.242.140.21)                                  
20-06-03_Jun:06:1591212555_-0400 1.0.0.127.new.spam.dnsbl.sorbs.net.    [blacklisted] (92.242.140.21)                                    
20-06-03_Jun:06:1591212555_-0400 1.0.0.127.noptr.spamrats.com.          [blacklisted] (92.242.140.21)                                    
20-06-03_Jun:06:1591212556_-0400 1.0.0.127.old.spam.dnsbl.sorbs.net.    [blacklisted] (92.242.140.21)                                    
20-06-03_Jun:06:1591212556_-0400 1.0.0.127.pbl.spamhaus.org.            [blacklisted] (92.242.140.21)                                    
20-06-03_Jun:06:1591212556_-0400 1.0.0.127.phishing.rbl.msrbl.net.      [blacklisted] (92.242.140.21)                                    
20-06-03_Jun:06:1591212556_-0400 1.0.0.127.pofon.foobar.hu.             [blacklisted] (92.242.140.21)                                    
20-06-03_Jun:06:1591212557_-0400 1.0.0.127.problems.dnsbl.sorbs.net.    [blacklisted] (92.242.140.21)                                    
20-06-03_Jun:06:1591212558_-0400 1.0.0.127.proxies.dnsbl.sorbs.net.     [blacklisted] (92.242.140.21)                                    
20-06-03_Jun:06:1591212559_-0400 1.0.0.127.psbl.surriel.com.            [blacklisted] (92.242.140.21)                                    
20-06-03_Jun:06:1591212559_-0400 1.0.0.127.rbl2.triumf.ca.              [blacklisted] (92.242.140.21)                                    
20-06-03_Jun:06:1591212559_-0400 1.0.0.127.rbl.abuse.ro.                [blacklisted] (92.242.140.21)                                    
20-06-03_Jun:06:1591212559_-0400 1.0.0.127.rbl.blockedservers.com.      [blacklisted] (92.242.140.21)                                    
20-06-03_Jun:06:1591212559_-0400 1.0.0.127.rbl.dns-servicios.com.       [blacklisted] (92.242.140.21)                                    
20-06-03_Jun:06:1591212559_-0400 1.0.0.127.rbl.efnet.org.               [blacklisted] (92.242.140.21)                                    
20-06-03_Jun:06:1591212560_-0400 1.0.0.127.rbl.efnetrbl.org.            [blacklisted] (92.242.140.21)                                    
20-06-03_Jun:06:1591212560_-0400 1.0.0.127.rbl.interserver.net.         [blacklisted] (92.242.140.21)                                    
20-06-03_Jun:06:1591212560_-0400 1.0.0.127.rbl.megarbl.net.             [blacklisted] (75.2.37.224)                                      
20-06-03_Jun:06:1591212560_-0400 1.0.0.127.rbl.realtimeblacklist.com.   [not listed]                                                     
20-06-03_Jun:06:1591212561_-0400 1.0.0.127.recent.spam.dnsbl.sorbs.net. [blacklisted] (92.242.140.21)                                    
20-06-03_Jun:06:1591212561_-0400 1.0.0.127.relays.dnsbl.sorbs.net.      [blacklisted] (92.242.140.21)                                    
20-06-03_Jun:06:1591212561_-0400 1.0.0.127.rep.mailspike.net.           [blacklisted] (92.242.140.21)                                    
20-06-03_Jun:06:1591212561_-0400 1.0.0.127.safe.dnsbl.sorbs.net.        [blacklisted] (92.242.140.21)                                    
20-06-03_Jun:06:1591212561_-0400 1.0.0.127.sbl.spamhaus.org.            [blacklisted] (92.242.140.21)                                    
20-06-03_Jun:06:1591212561_-0400 1.0.0.127.smtp.dnsbl.sorbs.net.        [blacklisted] (92.242.140.21)                                    
20-06-03_Jun:06:1591212561_-0400 1.0.0.127.socks.dnsbl.sorbs.net.       [blacklisted] (92.242.140.21)                                    
20-06-03_Jun:06:1591212561_-0400 1.0.0.127.spam.dnsbl.anonmails.de.     [blacklisted] (92.242.140.21)                                    
20-06-03_Jun:06:1591212561_-0400 1.0.0.127.spam.dnsbl.sorbs.net.        [blacklisted] (92.242.140.21)                                    
20-06-03_Jun:06:1591212562_-0400 1.0.0.127.spamlist.or.kr.              [blacklisted] (92.242.140.21)                                    
20-06-03_Jun:06:1591212562_-0400 1.0.0.127.spam.pedantic.org.           [blacklisted] (92.242.140.21)                                    
20-06-03_Jun:06:1591212562_-0400 1.0.0.127.spam.rbl.blockedservers.com. [blacklisted] (92.242.140.21)                                    
20-06-03_Jun:06:1591212562_-0400 1.0.0.127.spamrbl.imp.ch.              [blacklisted] (92.242.140.21)                                    
20-06-03_Jun:06:1591212562_-0400 1.0.0.127.spam.rbl.msrbl.net.          [blacklisted] (92.242.140.21)                                    
20-06-03_Jun:06:1591212562_-0400 1.0.0.127.spamsources.fabel.dk.        [blacklisted] (92.242.140.21)                                    
20-06-03_Jun:06:1591212562_-0400 1.0.0.127.spam.spamrats.com.           [blacklisted] (92.242.140.21)                                    
20-06-03_Jun:06:1591212562_-0400 1.0.0.127.srn.surgate.net.             [not listed]                                                     
20-06-03_Jun:06:1591212566_-0400 1.0.0.127.stabl.rbl.webiron.net.       [not listed]                                                     
20-06-03_Jun:06:1591212574_-0400 1.0.0.127.st.technovision.dk.          [not listed]                                                     
20-06-03_Jun:06:1591212574_-0400 1.0.0.127.talosintelligence.com.       [blacklisted] (92.242.140.21)                                    
20-06-03_Jun:06:1591212574_-0400 1.0.0.127.torexit.dan.me.uk.           [blacklisted] (92.242.140.21)                                    
20-06-03_Jun:06:1591212574_-0400 1.0.0.127.truncate.gbudb.net.          [blacklisted] (92.242.140.21)                                    
20-06-03_Jun:06:1591212574_-0400 1.0.0.127.ubl.unsubscore.com.          [blacklisted] (92.242.140.21)                                    
20-06-03_Jun:06:1591212574_-0400 1.0.0.127.virus.rbl.msrbl.net.         [blacklisted] (92.242.140.21)                                    
20-06-03_Jun:06:1591212574_-0400 1.0.0.127.web.dnsbl.sorbs.net.         [blacklisted] (92.242.140.21)                                    
20-06-03_Jun:06:1591212576_-0400 1.0.0.127.web.rbl.msrbl.net.           [blacklisted] (92.242.140.21)                                    
20-06-03_Jun:06:1591212576_-0400 1.0.0.127.xbl.spamhaus.org.            [blacklisted] (92.242.140.21)                                    
20-06-03_Jun:06:1591212576_-0400 1.0.0.127.zen.spamhaus.org.            [blacklisted] (92.242.140.21)                                    
20-06-03_Jun:06:1591212576_-0400 1.0.0.127.z.mailspike.net.             [blacklisted] (92.242.140.21)                                    
20-06-03_Jun:06:1591212576_-0400 1.0.0.127.zombie.dnsbl.sorbs.net.      [blacklisted] (92.242.140.21)

**Comment by adionditsak** [comment]
I can not reproduce this @BustedSec, please reopen if it persist
